name: deploy with eb development

on:
  push:
    branches:
      - prd
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'docs/**'

jobs:
  deploy:
    if: github.repository == 'proj-poppin/poppin-server'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create folder
        run: |
          mkdir -p src/main/resources

      - name: Create application yml File
        run: |
          echo '${{ secrets.AWS_PROPERTIES }}' > src/main/resources/application.yml

      - name: Create dev yml File
        run: |
          echo '${{ secrets.AWS_PRD_PROPERTIES }}' > src/main/resources/application-prd.yml

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Define Version
        run: echo "VERSION=v-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "AWS_S3_PRD_BUCKET_NAME is: $AWS_S3_PRD_BUCKET_NAME"
        env:
          AWS_S3_PRD_BUCKET_NAME: "poppin-deploy-bucket"

      - name: Upload JAR to S3 (with versioning)
        run: |
          aws s3 cp build/libs/poppin-server-0.0.1-SNAPSHOT.jar s3://poppin-deploy-bucket/app-${{ env.VERSION }}.jar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Generate Dockerrun.aws.json
        run: |
          cat <<EOF > Dockerrun.aws.json
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "openjdk:17-jdk-slim",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": "8080"
              }
            ],
            "Logging": "/var/log/nginx",
            "Command": "sh -c 'apt-get update && apt-get install -y awscli tzdata && \
              ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
              echo \"Asia/Seoul\" > /etc/timezone && \
              dpkg-reconfigure -f noninteractive tzdata && \
              mkdir -p /app && \
              while ! aws s3 cp s3://poppin-deploy-bucket/app-${{ env.VERSION }}.jar /app/app.jar; do \
                echo \"Retrying S3 download...\"; sleep 5; done && \
              java \$JAVA_OPTS -Dspring.profiles.active=prd -Duser.timezone=Asia/Seoul -jar /app/app.jar'"
            ,
            "Environment": [
              {
                "Name": "SPRING_PROFILES_ACTIVE",
                "Value": "prd"
              },
              {
                "Name": "TZ",
                "Value": "Asia/Seoul"
              },
              {
                "Name": "AWS_REGION",
                "Value": "$AWS_REGION"
              },
              {
                "Name": "AWS_ACCESS_KEY_ID",
                "Value": "$AWS_ACCESS_KEY_ID"
              },
              {
                "Name": "AWS_SECRET_ACCESS_KEY",
                "Value": "$AWS_SECRET_ACCESS_KEY"
              },
              {
                "Name": "JAVA_OPTS",
                "Value": "-Xms512m -Xmx2g"
              }
            ]
          }
          EOF

      - name: Package Dockerrun.aws.json into a ZIP file
        run: |
          mkdir -p deploy
          cp Dockerrun.aws.json deploy/
          cd deploy
          zip -r ../deploy-${{ env.VERSION }}.zip .

      - name: Upload ZIP file to S3
        run: |
          aws s3 cp deploy-${{ env.VERSION }}.zip s3://poppin-deploy-bucket/deploy-${{ env.VERSION }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Check if ZIP file exists in S3
        run: |
          echo "Checking if ZIP file exists in S3..."
          aws s3 ls s3://$AWS_S3_PRD_BUCKET_NAME/deploy-${{ env.VERSION }}.zip || { echo "ZIP file not found! Exiting..."; exit 1; }
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_PRD_BUCKET_NAME: ${{ secrets.AWS_S3_PRD_BUCKET_NAME }}

      - name: Wait for Elastic Beanstalk to Process Application Version
        run: |
          echo "Waiting for Elastic Beanstalk to process the new application version..."
          sleep 30

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name $EB_PRD_APP_NAME --version-label ${{ env.VERSION }} --source-bundle S3Bucket=$AWS_S3_PRD_BUCKET_NAME,S3Key=deploy-${{ env.VERSION }}.zip
          aws elasticbeanstalk update-environment --environment-name $EB_PRD_ENV_NAME --version-label ${{ env.VERSION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_PRD_APP_NAME: ${{ secrets.EB_PRD_APP_NAME }}
          EB_PRD_ENV_NAME: ${{ secrets.EB_PRD_ENV_NAME }}
          AWS_S3_PRD_BUCKET_NAME: ${{ secrets.AWS_S3_PRD_BUCKET_NAME }}

      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to complete..."
          # Sleep to allow deployment to finish
          sleep 180
          # Get the environment health status
          HEALTH=$(aws elasticbeanstalk describe-environments --environment-names $EB_PRD_ENV_NAME --query "Environments[0].Health" --output text)
          if [ "$HEALTH" != "Green" ]; then
            echo "Deployment health is not green. Current status: $HEALTH"
            exit 1
          fi
          echo "Deployment successful and environment is healthy!"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_PRD_ENV_NAME: ${{ secrets.EB_PRD_ENV_NAME }}